---
name: Test Container Builds

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:

  test_builds:
    name: Test Container Builds
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - pw_discord_bot
          - pw_ingest
          - pw_router
          - pw_ws_broker
        arch:
          - linux/amd64
          - linux/arm64

    steps:

      # Check out our code
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Get metadata from repo
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}

      # Set up QEMU for multi-arch builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # Set up buildx for multi platform builds
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      # Test Build
      - name: Test Build - ${{ matrix.image }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/${{ matrix.image }}/Dockerfile
          no-cache: true
          platforms: ${{ matrix.arch }}
          push: false
          tags: ghcr.io/${{ env.GHCR_IMAGE }}:${{ matrix.image }}_${{ matrix.arch }}
          labels: ${{ steps.meta.outputs.labels }}
