---
name: Publish Release

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  deploy_ghcr:
    name: Deploy ghcr.io (Multi-Arch)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - pw_discord_bot
          - pw_ingest
          - pw_router
          - pw_ws_broker

    steps:

      # Check out our code
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Log into ghcr (so we can push images)
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Get metadata from repo
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ matrix.image }}
          labels: |
            org.opencontainers.image.version=${{ github.ref_name }}

      # Set up QEMU for multi-arch builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # Set up buildx for multi platform builds
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      # Build & Push (if push to main branch)
      - name: Build & Push - ${{ matrix.image }}
        uses: docker/build-push-action@v2
        with:
          build-args: IMAGE_VERSION="${{ github.ref_name }}"
          context: .
          file: docker/${{ matrix.image }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ matrix.image }}:${{ github.ref_name }},ghcr.io/${{ matrix.image }}:latest
